server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: bookinfo
          uri: http://localhost:8081
          predicates:
            - Path=/bookInfos/** 
        - id: rental
          uri: http://localhost:8082
          predicates:
            - Path=/rentalManagements/** /bookinformations/**
        - id: delivery
          uri: http://localhost:8083
          predicates:
            - Path=/deliveryManagements/** 
        - id: Lookup
          uri: http://localhost:8084
          predicates:
            - Path= /rentalStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: bookinfo
          uri: http://bookinfo:8080
          predicates:
            - Path=/bookInfos/** 
        - id: rental
          uri: http://rental:8080
          predicates:
            - Path=/rentalManagements/** /bookinformations/**
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveryManagements/** 
        - id: Lookup
          uri: http://Lookup:8080
          predicates:
            - Path= /rentalStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
